In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import glob
import os
import numpy as np

from collections import Counter

# Loads each whole scenario as a sheet (For Later)

# Loads and seperates each car into its own sheet

In [8]:
start_folder = 'ScenarioScaled'
csvs = glob.glob(r'{}\*.csv'.format(start_folder))
df_list = []

for c in csvs:
    df = pd.read_csv(c)
    for i in np.unique(df.sender):
        df_list.append(df[df.sender.isin([i])].copy())
    #     df[df.ID.isin([subs[0]])&df.Vigil.isin(vigils[0])].copy()
print(len(df_list))
# df_list[0]

47539


In [20]:
csvs

['ScenarioScaled\\scenario_0.csv',
 'ScenarioScaled\\scenario_1.csv',
 'ScenarioScaled\\scenario_10.csv',
 'ScenarioScaled\\scenario_100.csv',
 'ScenarioScaled\\scenario_101.csv',
 'ScenarioScaled\\scenario_102.csv',
 'ScenarioScaled\\scenario_103.csv',
 'ScenarioScaled\\scenario_104.csv',
 'ScenarioScaled\\scenario_105.csv',
 'ScenarioScaled\\scenario_106.csv',
 'ScenarioScaled\\scenario_107.csv',
 'ScenarioScaled\\scenario_108.csv',
 'ScenarioScaled\\scenario_109.csv',
 'ScenarioScaled\\scenario_11.csv',
 'ScenarioScaled\\scenario_110.csv',
 'ScenarioScaled\\scenario_111.csv',
 'ScenarioScaled\\scenario_112.csv',
 'ScenarioScaled\\scenario_113.csv',
 'ScenarioScaled\\scenario_114.csv',
 'ScenarioScaled\\scenario_115.csv',
 'ScenarioScaled\\scenario_116.csv',
 'ScenarioScaled\\scenario_117.csv',
 'ScenarioScaled\\scenario_118.csv',
 'ScenarioScaled\\scenario_119.csv',
 'ScenarioScaled\\scenario_12.csv',
 'ScenarioScaled\\scenario_120.csv',
 'ScenarioScaled\\scenario_121.csv',
 'Scenar

In [11]:
df_list[10].iloc[:,[1,2,4,5,6,7]]

time  sender      pos0      pos1      spd0      spd1
116  10816.639813      67 -0.426269 -1.564897 -1.115847  1.110823
124  10817.639813      67 -0.431823 -1.451537 -1.116012  1.111016
132  10818.639813      67 -0.437377 -1.338180 -1.114965  1.109788
139  10819.639813      67 -0.442932 -1.224807 -1.116135  1.111161
146  10820.639813      67 -0.448488 -1.111434 -1.114471  1.109207
152  10821.639813      67 -0.452719 -0.997423 -0.889679  1.117464
159  10822.639813      67 -0.456852 -0.883399 -0.887683  1.114298
166  10823.639813      67 -0.460986 -0.769364 -0.889440  1.117085
173  10824.639813      67 -0.465119 -0.655369 -0.889729  1.117544
180  10825.639813      67 -0.469249 -0.541414 -0.888324  1.115315
187  10826.639813      67 -0.472846 -0.427285 -0.699269  1.119473
194  10827.639813      67 -0.475788 -0.312952 -0.699998  1.121103
201  10828.639813      67 -0.478731 -0.198575 -0.699978  1.121056
208  10829.639813      67 -0.481674 -0.084218 -0.700194  1.121539
215  10830.639813      67 -0.484616  0.030123 -0.700041  1.121197
223  10831.639813      67 -0.487560  0.144554 -0.698796  1.118416
232  10832.639813      67 -0.489066  0.259186 -0.469633  1.120537
241  10833.639813      67 -0.490571  0.373886 -0.470221  1.123116
249  10834.639813      67 -0.492074  0.488500 -0.469511  1.120001
258  10835.639813      67 -0.492968  0.603223 -0.235998  1.122179
268  10836.639813      67 -0.493003  0.717918 -0.236000  1.122629
279  10837.639813      67 -0.493038  0.832764 -0.236012  1.124869
290  10838.639813      67 -0.493073  0.947550 -0.235998  1.122130
301  10839.639813      67 -0.493108  1.062299 -0.236003  1.123103
312  10840.639813      67 -0.491676  1.176910  0.013881  1.122208
323  10841.639813      67 -0.489701  1.291491  0.196434  1.121218
335  10842.639813      67 -0.487024  1.405927  0.195272  1.118361
348  10843.639813      67 -0.484347  1.520404  0.196799  1.122115
361  10844.639813      67 -0.480807  1.634565  0.372029  1.116150
375  10845.639813      67 -0.477022  1.748661  0.372350  1.116708

# Note: you would find and organize the cars that are the closest right here and more the dataframe with that info now (Ex: for a given row with Car7 look N rows up and pick different carX with closest POS (Not Sped))

## ****.attackerType can be 1,2,4,8,16 and are different types of attacks May need to seperate out

In [12]:
df_attacker = []
df_normal = []
window_size = 11
overlap_size = 10

for j in df_list:
    if j.attackerType.any() == 0:
        j = j.iloc[:,[1,2,4,5,6,7]]
        for start_idx in range(0, len(j)-window_size, window_size - overlap_size):
            end_idx = start_idx + window_size
            df_chunk = j.iloc[start_idx:end_idx]
#             display(df_chunk)
            df_normal.append(df_chunk)
        
    
    elif j.attackerType.any() == 1:
        j = j.iloc[:,[5,6,14,15]]
        df_attacker.append(j)

# df_normal = np.asarray(df_normal)
# df_attacker = np.asarray(df_attacker)

df_normal[0]

time  sender      pos0      pos1      spd0      spd1
1   10800.437587       7 -0.466850 -0.607611 -0.908263  1.146953
8   10801.437587       7 -0.471098 -0.490409 -0.908228  1.146896
14  10802.437587       7 -0.474247 -0.372840 -0.713143  1.150487
20  10803.437587       7 -0.477275 -0.255153 -0.712426  1.148884
26  10804.437587       7 -0.480302 -0.137515 -0.712289  1.148578
32  10805.437587       7 -0.483330 -0.019843 -0.711866  1.147633
39  10806.437587       7 -0.486357  0.097775 -0.712726  1.149555
45  10807.437587       7 -0.488495  0.215632 -0.476734  1.151681
52  10808.437587       7 -0.490041  0.333521 -0.477325  1.154273
59  10809.437587       7 -0.491588  0.451445 -0.476311  1.149825
66  10810.437587       7 -0.492958  0.569303 -0.285300  1.153551

In [15]:
len(df_normal)
df_normal[12]

time  sender      pos0      pos1      spd0      spd1
13  10802.392785      13 -0.489258  0.055667 -0.839245  1.432360
19  10803.392785      13 -0.492323  0.204330 -0.541268  1.433327
25  10804.392785      13 -0.494277  0.353187 -0.541382  1.433824
31  10805.392785      13 -0.496232  0.502096 -0.541444  1.434097
38  10806.392785      13 -0.496960  0.651186 -0.237663  1.437887
44  10807.392785      13 -0.497005  0.800238 -0.237655  1.436284
51  10808.392785      13 -0.497051  0.949381 -0.237660  1.437325
58  10809.392785      13 -0.496705  1.098526  0.087176  1.434075
65  10810.392785      13 -0.494707  1.247491  0.087748  1.436531
73  10811.392785      13 -0.491239  1.396212  0.322483  1.433137
81  10812.392785      13 -0.487767  1.544870  0.323065  1.434569

# Next take df_normal and for each element in it put 10 rows in X and 1 row into Y (Convert to numpy) For Model 1

In [19]:
X[0]

array([[-0.46684979, -0.60761065, -0.90826326,  1.14695297],
       [-0.47109841, -0.49040891, -0.90822753,  1.14689626],
       [-0.47424717, -0.37283967, -0.71314296,  1.15048657],
       [-0.47727534, -0.25515343, -0.71242595,  1.14888376],
       [-0.48030228, -0.1375154 , -0.71228921,  1.1485781 ],
       [-0.48333009, -0.01984312, -0.71186626,  1.14763262],
       [-0.48635652,  0.09777536, -0.71272623,  1.14955501],
       [-0.48849523,  0.21563232, -0.47673441,  1.15168105],
       [-0.4900413 ,  0.33352078, -0.47732537,  1.15427292],
       [-0.49158783,  0.45144506, -0.47631126,  1.14982518]])

In [16]:
X = []
y = []
for df in df_normal:
    X.append(np.asarray(df.iloc[0:10,2:]))
    y.append(np.asarray(df.iloc[10,2:]))
X = np.asarray(X)
y = np.asarray(y)
np.save(r'{}\X_scaled.npy'.format(start_folder), X)
np.save(r'{}\y_scaled.npy'.format(start_folder), y)

In [24]:
X1 = np.load(r'{}\y_scaled.npy'.format(start_folder))
X1.shape

(1196218, 4)

In [15]:
X1 = np.load(r'C:\Users\aidan\Desktop\5G-BSM-Threat-Detection\{}\X.npy'.format(start_folder))
X1.shape

(1196218, 10, 4)

In [16]:
X1[0]

array([[ 3.60939849e+03,  5.44680326e+03, -3.53405773e+00,
         3.06222342e+01],
       [ 3.60587337e+03,  5.47734809e+03, -3.53387139e+00,
         3.06206197e+01],
       [ 3.60326082e+03,  5.50798869e+03, -2.51674686e+00,
         3.07228422e+01],
       [ 3.60074831e+03,  5.53865978e+03, -2.51300856e+00,
         3.06772074e+01],
       [ 3.59823683e+03,  5.56931832e+03, -2.51229565e+00,
         3.06685046e+01],
       [ 3.59572462e+03,  5.59998577e+03, -2.51009046e+00,
         3.06415851e+01],
       [ 3.59321356e+03,  5.63063921e+03, -2.51457414e+00,
         3.06963190e+01],
       [ 3.59143905e+03,  5.66135479e+03, -1.28416894e+00,
         3.07568515e+01],
       [ 3.59015626e+03,  5.69207859e+03, -1.28725005e+00,
         3.08306467e+01],
       [ 3.58887309e+03,  5.72281172e+03, -1.28196275e+00,
         3.07040115e+01]])

In [17]:
X1[30]

array([[ 3.82936674e+03,  5.26232798e+03,  5.06028439e+00,
        -3.48143023e+00],
       [ 3.83537483e+03,  5.25819446e+03,  6.94068123e+00,
        -4.77512637e+00],
       [ 3.84336042e+03,  5.25280902e+03,  9.14090422e+00,
        -6.02007260e+00],
       [ 3.85358731e+03,  5.24721513e+03,  1.20621312e+01,
        -4.81824196e+00],
       [ 3.86744993e+03,  5.24855892e+03,  1.47329413e+01,
         2.08237175e+00],
       [ 3.88184276e+03,  5.25059322e+03,  1.47054407e+01,
         2.07848477e+00],
       [ 3.89622224e+03,  5.25262563e+03,  1.46322612e+01,
         2.06814150e+00],
       [ 3.91059872e+03,  5.25465762e+03,  1.46733947e+01,
         2.07395536e+00],
       [ 3.92499009e+03,  5.25669171e+03,  1.47283264e+01,
         2.08171948e+00],
       [ 3.93940498e+03,  5.25872913e+03,  1.47675056e+01,
         2.08725711e+00]])